[project]
name = "RiscVOS"
version = "0.1"
arch = "riscv64"
cross_compile = "riscv64-unknown-elf-"

[drivers]
[drivers.virtio]
type = "builtin"
[drivers.virtio.config]
ring_size = 4096
queue_size = 128

[fs]
[fs.fat32]
mbr = true
label = "rootfs"
path = "src/Userland/RootFS"
